# Generated by Django 3.0.5 on 2020-05-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='default', max_length=255, verbose_name='Фамилия пользователя'),
            preserve_default=False,
        ),
    ]
